### ISSUE TITLE
connection not working since 1.3

### ISSUE THREAD

**Issue by karlbeecken** [ThomDietrich/home-assistant-addons#24]
Hi, since the update to 1.3.2 the connection does not work anymore. The addon just tells me this: 
![image](https://github.com/user-attachments/assets/a22c6857-ce1c-4cca-8df7-0c71882be4e2)

And then stops.

My current config:

```yaml
hostname: <redacted>
ssh_port: 22
username: sshtunnel
remote_ip_address: 127.0.0.1
remote_port: 8123
other_ssh_options: "-v"
force_keygen: false
remote_forwarding: []
local_port: 443
```

When I check on the remote server with `journalctl -fu ssh` I don't see any connection attempts from my ip or the user `sshtunnel`, so I suspect an issue in the addon.
