### ISSUE TITLE
502 Bad-gateway - directly after updating from 1.2.1 to 1.3.3 / 1.3.4 -- downgrading -> 1.2.1 .. working again 

### ISSUE THREAD

**Issue by fraban** [ThomDietrich/home-assistant-addons#28]
Hi - short review … first I made my remotes manually ..  since 3 years I use your add-on on several systems. Great and easy.
Still yesterday I updated 2 systems from 1.2.1 to 1.3.3 … 1.3.4
After update I got on both HA-Systems 502 Bad Gateway …
My nginx - server I was coming from told me in the log:

“GET /config/dashboard HTTP/2.0” 502 157 “https://hassio.xyzmydomain.com/sw-modern.js” "Mozilla/5.0 (Mac …
Here in the log I can see the 502 - Bad gateway …

Short solution for me_. Backup install Version 1.2.1.

Now nginx-Log shows and is working
“GET /api/hassio/addons/5da1ffb2_autossh/icon HTTP/2.0” 200 3619 “https://hassio.xyzmydomain.com/config/dashboard” "Mozilla/5.

So downgrading fixed my 502-gateway problem immediately …

Can you imagine what happens when doing the update to 1.3.3 or .1.3.4 - where is the change , getting 502-Bad gateway …

So that’s my thing with 1.3.3 and 1.3.4 Versions - not working - still on 1.2.1 at the moment.
I hope this log is helping fixing the issue - or is it only me having this ?
Thanks and Regards
Frank

**Comment by ThomDietrich** [comment]
Hey Frank!
The changes from 1.3.x to 1.3.4 are minor and bugfixes, however none related to your issue.
Your log from the addon would be interesting. Could you copy that one over?

I suspect this is an issue with your config, which received some love with Version 1.3. When cleaned and sorted it should look something like this:

```yaml
hostname: ssh.yourdomain.com
ssh_port: 2222
username: homeassistant
remote_ip_address: 127.0.0.1
remote_port: 8888
other_ssh_options: "-N"
force_keygen: false
remote_forwarding: []
```
